name: steam_notifications_example
description: Example app demonstrating steam_notifications package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  steam_notifications:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
